const v56ServerSnapshotFixture = <String, dynamic>{
  'account': <String, dynamic>{
    'id': '11111111-1111-4111-8111-111111111111',
    'brokerCode': 'botx-paper',
    'platform': 'PAPER',
    'environment': 'paper',
    'accountNumberMasked': 'SERVER-TEST',
    'currency': 'USD',
    'balance': '10000',
    'equity': '10000',
    'freeMargin': '10000',
    'usedMargin': '0',
    'openPnl': '0',
    'realizedPnl': '0',
    'stale': false,
    'riskWindowComplete': true,
    'tradingPermission': true,
  },
  'brokerAccounts': <Map<String, dynamic>>[
    <String, dynamic>{
      'id': '11111111-1111-4111-8111-111111111111',
      'brokerCode': 'botx-paper',
      'platform': 'PAPER',
      'environment': 'paper',
      'accountNumberMasked': 'SERVER-TEST',
      'sessionState': 'healthy',
    },
  ],
  'connection': <String, dynamic>{
    'state': 'healthy',
    'label': 'server-test-fixture',
  },
  'riskState': <String, dynamic>{
    'drawdownPct': '0',
    'maxRiskPerTradePct': '1',
  },
  'latencyState': <String, dynamic>{'p95AckMs': '21'},
  'openOrders': <Map<String, dynamic>>[],
  'pendingOrders': <Map<String, dynamic>>[],
  'closedOrders': <Map<String, dynamic>>[],
  'bots': <Map<String, dynamic>>[
    <String, dynamic>{
      'id': '22222222-2222-4222-8222-222222222222',
      'bot_type': 'DCA',
      'instance_name': 'DCA Test #01',
      'symbol': 'XAUUSD',
      'state': 'running',
      'environment': 'paper',
      'pnl': '0',
      'investment': '500',
      'trades': 0,
      'broker_name': 'BotX Paper',
      'account_number_masked': 'SERVER-TEST',
      'execution_timing': 'server-authoritative',
    },
  ],
  'market': <Map<String, dynamic>>[],
};
